server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: proxy requests to backend if we don't want to expose backend port directly
    # location /api/ {
    #     proxy_pass http://backend:8000/;
    # }
}
